/**
 * playWelcomeChime — plays the ElevenLabs-generated startup chime once.
 * File: public/audio/sfx/welcome_chime.mp3 (generated by scripts/generate-audio.py)
 */
export function playWelcomeChime(): void {
  try {
    const audio  = new Audio("/audio/sfx/welcome_chime.mp3");
    audio.volume = 0.8;
    audio.play().catch(() => {});
  } catch {/* silent */}
}
