/**
 * speak — Hebrew TTS with pre-recorded voice file priority.
 *
 * Priority:
 *   1. Pre-recorded MP3 from /audio/voices/ (generated by scripts/generate-audio.py)
 *   2. Browser Web Speech API (he-IL) as fallback
 *
 * Voice modes (used for Web Speech fallback):
 *   "instruction"   — rate 0.78, pitch 1.05
 *   "letter"        — rate 0.68, pitch 1.08  (slowest — isolated pronunciation)
 *   "number"        — rate 0.70, pitch 1.06
 *   "encouragement" — rate 0.88, pitch 1.12  (warm, upbeat)
 *   "syllable"      — rate 0.62, pitch 1.05  (very slow — hear each part)
 */

export type VoiceMode = "instruction" | "letter" | "number" | "encouragement" | "syllable";

const VOICE_CONFIG: Record<VoiceMode, { rate: number; pitch: number }> = {
  instruction:   { rate: 0.78, pitch: 1.05 },
  letter:        { rate: 0.68, pitch: 1.08 },
  number:        { rate: 0.70, pitch: 1.06 },
  encouragement: { rate: 0.88, pitch: 1.12 },
  syllable:      { rate: 0.62, pitch: 1.05 },
};

// ── Pre-recorded voice file map ───────────────────────────────────────────────
// Keys are the exact Hebrew strings passed to speak().
// Values are filenames in /audio/voices/.
// Generated by: scripts/generate-audio.py

const VOICE_FILES: Record<string, string> = {
  // Welcome
  "הֵי גֶּפֶן! מַה שְּׁלוֹמֵךְ? אַת רוֹצָה לְהַתְחִיל לְשַׂחֵק?": "welcome_speech.mp3",
  "הֵי גֶּפֶן! מַה שְּׁלוֹמֵךְ?":                                          "greeting_gefen.mp3",

  // Numbers
  "אֶחָד":     "num_1.mp3",
  "שְׁתַּיִם":  "num_2.mp3",
  "שָׁלוֹשׁ":   "num_3.mp3",
  "אַרְבַּע":   "num_4.mp3",
  "חָמֵשׁ":     "num_5.mp3",
  "שֵׁשׁ":      "num_6.mp3",
  "שֶׁבַע":     "num_7.mp3",
  "שְׁמוֹנֶה":  "num_8.mp3",
  "תֵּשַׁע":    "num_9.mp3",
  "עֶשֶׂר":     "num_10.mp3",

  // Encouragement
  "כָּל הַכָּבוֹד!":            "enc_kol_hakavod.mp3",
  "!כָּל הַכָּבוֹד":            "enc_kol_hakavod.mp3",
  "!כל הכבוד":                  "enc_kol_hakavod.mp3",
  "נִפְלָא!":                   "enc_nifla.mp3",
  "!נִפְלָא":                   "enc_nifla.mp3",
  "מַדְהִים!":                  "enc_madim.mp3",
  "נְנַסֶּה יַחַד!":            "enc_nenase.mp3",
  "נְנַסֶּה יַחַד! 💛":         "enc_nenase.mp3",
  "שָׁלוֹשׁ בְּרֶצֶף! מַדְהִים!": "enc_streak.mp3",
  "!שלוש ברצף — מדהים":         "enc_streak.mp3",
  "יָפֶה מְאוֹד!":              "enc_yafe.mp3",

  // Instructions — Counting Garden
  "סִפְרִי אֶת הַפְּרָחִים!":   "inst_count_flowers.mp3",
  "כַּמָּה פְּרָחִים יֵשׁ?":     "inst_how_many.mp3",
  "בּוֹאִי נִסְפּוֹר יַחַד!":   "inst_lets_count.mp3",

  // Letter names
  "אָלֶף":  "letter_alef.mp3",
  "בֵּית":  "letter_bet.mp3",
  "גִּימֶל": "letter_gimel.mp3",

  // Letter intro instructions
  "הָאוֹת אָלֶף":  "inst_letter_alef.mp3",
  "הָאוֹת בֵּית":  "inst_letter_bet.mp3",
  "הָאוֹת גִּימֶל": "inst_letter_gimel.mp3",
  "מִי הָאוֹת אָלֶף? לַחְצִי עָלֶיהָ!":   "inst_who_alef.mp3",
  "מִי הָאוֹת בֵּית? לַחְצִי עָלֶיהָ!":   "inst_who_bet.mp3",
  "מִי הָאוֹת גִּימֶל? לַחְצִי עָלֶיהָ!":  "inst_who_gimel.mp3",

  // Syllables
  "אֵם": "syl_em.mp3",
  "בֵּן": "syl_ben.mp3",
  "גַּן": "syl_gan.mp3",

  // Letter complete
  "כָּל הַכָּבוֹד! לָמַדְתְּ אֶת הָאוֹת אָלֶף!":     "lc_alef.mp3",
  "כָּל הַכָּבוֹד! לָמַדְתְּ אֶת הָאוֹת בֵּית!":     "lc_bet.mp3",
  "כָּל הַכָּבוֹד! לָמַדְתְּ אֶת הָאוֹת גִּימֶל!":    "lc_gimel.mp3",
  "!סִיַּמְתְּ אֶת כָּל הָאוֹתִיּוֹת! כָּל הַכָּבוֹד": "lc_all.mp3",


  // Instructions — Addition Bubbles
  "בּוֹאִי נְחַבֵּר יַחַד!": "inst_lets_add.mp3",
  "כַּמָּה זֶה בְּיַחַד?": "inst_how_many_together.mp3",
  "לַחְצִי עַל הַבּוּעָה הַנְּכוֹנָה!": "inst_tap_bubble.mp3",
  // Trace / connect instructions
  "עִקְבִי אַחֲרֵי הַנְּקֻדּוֹת לְפִי הַסֵּדֶר":        "inst_trace.mp3",
  "אֵיזוֹ אוֹת זוֹ? לַחְצִי עָלֶיהָ!":                  "inst_trace.mp3",

  // Addition Bubbles — question voice lines (all reachable a+b pairs)
  "כַּמָּה זֶה אֶחָד וְעוֹד אֶחָד?": "add_q_1_1.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד שְׁתַּיִם?": "add_q_1_2.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד שָׁלוֹשׁ?": "add_q_1_3.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד אַרְבַּע?": "add_q_1_4.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד חָמֵשׁ?": "add_q_1_5.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד שֵׁשׁ?": "add_q_1_6.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד שֶׁבַע?": "add_q_1_7.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד שְׁמוֹנֶה?": "add_q_1_8.mp3",
  "כַּמָּה זֶה אֶחָד וְעוֹד תֵּשַׁע?": "add_q_1_9.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד אֶחָד?": "add_q_2_1.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד שְׁתַּיִם?": "add_q_2_2.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד שָׁלוֹשׁ?": "add_q_2_3.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד אַרְבַּע?": "add_q_2_4.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד חָמֵשׁ?": "add_q_2_5.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד שֵׁשׁ?": "add_q_2_6.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד שֶׁבַע?": "add_q_2_7.mp3",
  "כַּמָּה זֶה שְׁתַּיִם וְעוֹד שְׁמוֹנֶה?": "add_q_2_8.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד אֶחָד?": "add_q_3_1.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד שְׁתַּיִם?": "add_q_3_2.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד שָׁלוֹשׁ?": "add_q_3_3.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד אַרְבַּע?": "add_q_3_4.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד חָמֵשׁ?": "add_q_3_5.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד שֵׁשׁ?": "add_q_3_6.mp3",
  "כַּמָּה זֶה שָׁלוֹשׁ וְעוֹד שֶׁבַע?": "add_q_3_7.mp3",
  "כַּמָּה זֶה אַרְבַּע וְעוֹד אֶחָד?": "add_q_4_1.mp3",
  "כַּמָּה זֶה אַרְבַּע וְעוֹד שְׁתַּיִם?": "add_q_4_2.mp3",
  "כַּמָּה זֶה אַרְבַּע וְעוֹד שָׁלוֹשׁ?": "add_q_4_3.mp3",
  "כַּמָּה זֶה אַרְבַּע וְעוֹד אַרְבַּע?": "add_q_4_4.mp3",
  "כַּמָּה זֶה אַרְבַּע וְעוֹד חָמֵשׁ?": "add_q_4_5.mp3",
  "כַּמָּה זֶה אַרְבַּע וְעוֹד שֵׁשׁ?": "add_q_4_6.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד אֶחָד?": "add_q_5_1.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד שְׁתַּיִם?": "add_q_5_2.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד שָׁלוֹשׁ?": "add_q_5_3.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד אַרְבַּע?": "add_q_5_4.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד חָמֵשׁ?": "add_q_5_5.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד שֵׁשׁ?": "add_q_5_6.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד שֶׁבַע?": "add_q_5_7.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד שְׁמוֹנֶה?": "add_q_5_8.mp3",
  "כַּמָּה זֶה חָמֵשׁ וְעוֹד תֵּשַׁע?": "add_q_5_9.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד אֶחָד?": "add_q_6_1.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד שְׁתַּיִם?": "add_q_6_2.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד שָׁלוֹשׁ?": "add_q_6_3.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד אַרְבַּע?": "add_q_6_4.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד חָמֵשׁ?": "add_q_6_5.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד שֵׁשׁ?": "add_q_6_6.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד שֶׁבַע?": "add_q_6_7.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד שְׁמוֹנֶה?": "add_q_6_8.mp3",
  "כַּמָּה זֶה שֵׁשׁ וְעוֹד תֵּשַׁע?": "add_q_6_9.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד אֶחָד?": "add_q_7_1.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד שְׁתַּיִם?": "add_q_7_2.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד שָׁלוֹשׁ?": "add_q_7_3.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד אַרְבַּע?": "add_q_7_4.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד חָמֵשׁ?": "add_q_7_5.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד שֵׁשׁ?": "add_q_7_6.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד שֶׁבַע?": "add_q_7_7.mp3",
  "כַּמָּה זֶה שֶׁבַע וְעוֹד שְׁמוֹנֶה?": "add_q_7_8.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד אֶחָד?": "add_q_8_1.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד שְׁתַּיִם?": "add_q_8_2.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד שָׁלוֹשׁ?": "add_q_8_3.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד אַרְבַּע?": "add_q_8_4.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד חָמֵשׁ?": "add_q_8_5.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד שֵׁשׁ?": "add_q_8_6.mp3",
  "כַּמָּה זֶה שְׁמוֹנֶה וְעוֹד שֶׁבַע?": "add_q_8_7.mp3",
  "כַּמָּה זֶה תֵּשַׁע וְעוֹד אֶחָד?": "add_q_9_1.mp3",
  "כַּמָּה זֶה תֵּשַׁע וְעוֹד שְׁתַּיִם?": "add_q_9_2.mp3",
  "כַּמָּה זֶה תֵּשַׁע וְעוֹד שָׁלוֹשׁ?": "add_q_9_3.mp3",
  "כַּמָּה זֶה תֵּשַׁע וְעוֹד אַרְבַּע?": "add_q_9_4.mp3",
  "כַּמָּה זֶה תֵּשַׁע וְעוֹד חָמֵשׁ?": "add_q_9_5.mp3",
  "כַּמָּה זֶה תֵּשַׁע וְעוֹד שֵׁשׁ?": "add_q_9_6.mp3",
};

// ── Audio element pool (for overlapping / instant playback) ──────────────────

let currentVoice: HTMLAudioElement | null = null;

function playVoiceFile(filename: string): void {
  try {
    if (currentVoice) {
      currentVoice.pause();
      currentVoice.currentTime = 0;
    }
    const audio = new Audio(`/audio/voices/${filename}`);
    audio.volume = 1.0;
    audio.play().catch(() => {/* autoplay blocked */});
    currentVoice = audio;
  } catch {/* silent */}
}

// ── Web Speech API fallback ───────────────────────────────────────────────────

let _cachedVoice: SpeechSynthesisVoice | null | undefined = undefined;

function getHebrewVoice(): SpeechSynthesisVoice | null {
  if (_cachedVoice !== undefined) return _cachedVoice;
  const voices = window.speechSynthesis?.getVoices() ?? [];
  _cachedVoice =
    voices.find(v => v.lang === "he-IL") ??
    voices.find(v => v.lang.startsWith("he")) ??
    null;
  return _cachedVoice;
}

if (typeof window !== "undefined" && "speechSynthesis" in window) {
  window.speechSynthesis.onvoiceschanged = () => {
    _cachedVoice = undefined;
    getHebrewVoice();
  };
}

function speakTTS(text: string, mode: VoiceMode): void {
  if (!("speechSynthesis" in window)) return;
  window.speechSynthesis.cancel();
  const { rate, pitch } = VOICE_CONFIG[mode];
  const u   = new SpeechSynthesisUtterance(text);
  u.lang    = "he-IL";
  u.rate    = rate;
  u.pitch   = pitch;
  u.volume  = 1.0;
  const voice = getHebrewVoice();
  if (voice) u.voice = voice;
  window.speechSynthesis.speak(u);
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * speak — plays a pre-recorded voice file if available, otherwise uses TTS.
 */
export function speak(text: string, mode: VoiceMode = "instruction"): void {
  // Strip emoji / punctuation variants for lookup
  const clean = text.trim();
  const file  = VOICE_FILES[clean];
  if (file) {
    playVoiceFile(file);
    return;
  }
  speakTTS(text, mode);
}

/** Stop any in-progress speech. */
export function stopSpeech(): void {
  currentVoice?.pause();
  currentVoice = null;
  window.speechSynthesis?.cancel();
}

// ── Hebrew numbers (with nikud) ───────────────────────────────────────────────

export const HEBREW_NUMBERS = [
  "",              // 0 — unused
  "אֶחָד",         // 1
  "שְׁתַּיִם",      // 2
  "שָׁלוֹשׁ",       // 3
  "אַרְבַּע",       // 4
  "חָמֵשׁ",         // 5
  "שֵׁשׁ",          // 6
  "שֶׁבַע",         // 7
  "שְׁמוֹנֶה",      // 8
  "תֵּשַׁע",        // 9
  "עֶשֶׂר",         // 10
  "אַחַת עֶשְׂרֵה",  // 11
  "שְׁתֵּים עֶשְׂרֵה", // 12
  "שְׁלוֹשׁ עֶשְׂרֵה", // 13
  "אַרְבַּע עֶשְׂרֵה", // 14
  "חֲמֵשׁ עֶשְׂרֵה",   // 15
];
